AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Backend FastAPI como contenedor Lambda

Resources:
  WalletAPI:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Timeout: 30
      Role: arn:aws:iam::946973317280:role/LabRole  # ⚠️ Este debe ser el rol válido
      KmsKeyArn: !Ref AWS::NoValue
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: python3.12-v1
